### PR TITLE
Tuples

### PR DESCRIPTION
**Pull request by gdotdesign**
This PR implements [**tuples**](https://en.wikipedia.org/wiki/Tuple) for the language #193. Tuples are fixed fixed sets of values which can be different types. Tuples are represented internally as arrays.

Tuples can be destructured in three places:
- `try`, `sequence` and `parallel` expressions
- `where` statements
- `case` statements

The syntax for a tuple looks like this: 
```
{"A", 0, true}
```
They resolve into the `Tuple` type where the parameters are types of it's members, for the example above:
```
Tuple(String, Number, Bool)
```

-----------------------

`Ast::Tuple`:
- [x] Parser
- [x] Type Checker 
- [x] Formatter
- [x] Compiler

`try`, `sequence` and `parallel` destructuring:
- [x] Modify `Ast::Statement` to handle destructuring
- [x] Modify `Ast::Try`, `Ast::Sequence`, `Ast::Parallel` to resolve destructuring
- [x] Raise error when trying to destructure more variables than available
- [x] Raise error when trying to destructure a none `Tuple` 

`where` destructuring:
- [x] Modify `Ast::WhereStatement` to allow for destructuring
- [x] Raise error when trying to destructure more variables than available
- [x] Raise error when trying to destructure a none `Tuple` 

`case` destructuring:
- [x] Add `Ast::TupleDestructuring`
  - [x] Parser
  - [x] Type Checker 
  - [x] Formatter
- [x] Modify `Ast::CaseBranch` to resolve tuple destructuring
- [x] Raise error when trying to destructure a none `Tuple`

### CODE REVIEW

**Comment by gdotdesign** [comment]
This is pretty much done :tada: @Namek can you test it if it fits your use-cases?

**Comment by gdotdesign** [comment]
@Sija would you mind review it? :slightly_smiling_face:

**Comment by Namek** [comment]
First test: it works. But I will have more time on weekend to work with this some more. 

This might look weird:
```
if (condition) {
  { x + 1, y }
} else {
  { x, y + 1 }
}
```

with one-liner formatting:

```
if (condition) { { x + 1, y } } else { { x, y + 1 } }
```

**Comment by gdotdesign** [comment]
I've udpated the PR with some refactoring with the additional change that destructuring needs to be wrapped in `{}` like this:

```
{a, b, c} => {"A, "B", "C"}
```

This is to match the array destructuring semantics #210

**Comment by Sija** [comment]
Same https://github.com/mint-lang/mint/pull/210#issuecomment-592022688 applies here.

**Comment by Namek** [comment]
The record update syntax may behave wrong. I wrote code as such:

```
{genState |
  fieldsIndices = Array.push(idx, genState.fieldsIndices),
  fieldsMap = Map.set(idx, FieldType::Island(idx), genState.fieldsMap)
}
```

and absolutely no error/text was displayed in the browser nor the console. Just an empty gray rounded rectangle on red background appeared. The issue is lack of space between `{` and `genState`.

**Comment by gdotdesign** [comment]
This happens when either the base `SyntaxError` or `TypeError` class is raised, I'll try to track it down.

**Comment by Namek** [comment]
Another, similar one:

```
{num >= genState.chanceToPickExistingIsland, rand1}
```

The first tuple item is supposed to be a boolean expression. Auto-formatter removes the space after `{` and I get the same empty error.

Gets fixed when I move expression to a variable.

```
shouldPickExistingIsland =
  num >= genState.chanceToPickExistingIsland

{shouldPickExistingIsland, rand1}
```

**Comment by Namek** [comment]
Got a new issue: functions defined inside `where` block are not type-checked. It seems to be a regression since it behaves properly on the Sandbox: https://sandbox.mint-lang.com/sandboxes/odStFrMXwJMkLw

```
module Test {
  fun test1(a : Number) : String {
  	""
  } where {
  	test2 = (a : Number) : String {
      0
    }
  }
}
```

The `test2` function should fail compilation.

**Comment by Namek** [comment]
BTW I'm testing the array destructuring branch but report tuples here.

**Comment by gdotdesign** [comment]
@Namek do you have a SSCCE for the empty error?

**Comment by gdotdesign** [comment]
I've resolved the regression in the `array-destructuring` PR since it's ahead.

**Comment by gdotdesign** [comment]
@Namek managed to track the empty error down.

**Pull request merged**
